name: x_o
description: "A new Flutter project."
 
publish_to: 'none'  

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.11.0
  dartz: ^0.10.1
  equatable: ^2.1.0
  internet_connection_checker: ^3.0.1
  google_fonts: ^8.2.1
  shared_preferences: ^2.5.5
  cached_network_image: ^3.4.1
  pretty_dio_logger: ^1.4.0
  flutter_svg: ^2.3.0
  shimmer: ^3.0.0
  url_launcher: ^6.3.2
  path_provider: ^2.1.6
  connectivity_plus: ^6.1.5
  easy_localization: ^3.0.8
  animate_do: ^5.1.0
  lottie: ^3.5.1
  intl: ^0.20.2
  flutter_bloc: ^9.1.1
  bloc: ^9.2.1
  firebase_core: ^4.13.0
  firebase_auth: ^6.5.7
  cloud_firestore: ^6.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lang/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/fonts/CustomFont-Regular.ttf
        - asset: assets/fonts/CustomFont-Bold.ttf
          weight: 700