// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN5TNjtzIsZ7IA-hG7cIzG2_1TGaslQAI',
    appId: '1:175648750739:web:a61f4ebb021a4e5bfaa166',
    messagingSenderId: '175648750739',
    projectId: 'x-o-game-52255',
    authDomain: 'x-o-game-52255.firebaseapp.com',
    storageBucket: 'x-o-game-52255.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5vNXja3msJVTTvxEMzST1YVP6EcRL-1s',
    appId: '1:175648750739:android:69fa728eae00e399faa166',
    messagingSenderId: '175648750739',
    projectId: 'x-o-game-52255',
    storageBucket: 'x-o-game-52255.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRixtfcOb9IuOEgmzn7WMlPIrSp4RtZOw',
    appId: '1:175648750739:ios:7a209505c36627a6faa166',
    messagingSenderId: '175648750739',
    projectId: 'x-o-game-52255',
    storageBucket: 'x-o-game-52255.firebasestorage.app',
    iosBundleId: 'com.example.xo',
  );
}
